# Generated by Django 2.2.6 on 2019-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.CharField(max_length=100, verbose_name='Cid')),
                ('title', models.CharField(default='[notitle]', max_length=100, verbose_name='title')),
                ('summary', models.CharField(default='', max_length=200, verbose_name='summary')),
            ],
        ),
    ]
